const pages = [
  { location: '/', file: 'index',      page: 'index' },
  { location: '/data-format-example', file: 'data-format-example' },
  { location: '/scatterplot',         file: 'scatterplot' },
  { location: '/confetti',            file: 'confetti' },
  { location: '/rings',               file: 'rings' },
  { location: '/lines',               file: 'lines' },
  { location: '/scaled-lines',        file: 'scaled-lines' },
  { location: '/line-chart-1',        file: 'line-chart-1' },
  { location: '/time-line-chart',     file: 'time-line-chart' },
  { location: '/area-chart',          file: 'area-chart' },
  { location: '/area-chart-2',        file: 'area-chart-2' },
  { location: '/animated-line',       file: 'animated-line' },
  { location: '/animated-line-chart', file: 'animated-line-chart' },
  { location: '/my-name',             file: 'my-name' },
  { location: '/peace',               file: 'peace' },
  { location: '/pie2',                file: 'pie2' },
  { location: '/planet-diameters',    file: 'planet-diameters' },
  { location: '/game-scores',         file: 'game-scores' },
  { location: '/flower-pedal-pie',     file: 'flower-pedal-pie' },
  { location: '/stacked-bars',        file: 'stacked-bars' },
  { location: '/dom-1',               file: 'dom-1' },
  { location: '/dom-2',               file: 'dom-2' },
  { location: '/dom-3',               file: 'dom-3' },
  { location: '/binary-tree',         file: 'binary-tree' },
  { location: '/one-circle',          file: 'one-circle' },
  { location: '/one-line',            file: 'one-line' },
  { location: '/one-bar',             file: 'one-bar' },
  { location: '/five-little-circles',  file: 'five-little-circles' }
]

module.exports = pages
